# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Print hello world
      run: echo Hello, github actions
    - name: Grant execute permission for helloworld
      run: chmod +x ./bin/helloactions.sh
    - name: run helloworld script
      run: ./bin/helloactions.sh
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
#    - name: print helloGradle
#      run: ./gradlew helloActions
    - name: Build with Gradle
      run: ./gradlew clean build
